#!/bin/bash
set -euo pipefail

# Description: downloads data generated by basespace SMPv2 app
# using basespace command line interface (version 2)
# Author: Christopher Medway

version="1.1.3"

if [ ! -e "./appsessions.txt" ]; then echo "cannot locate appsessions.txt"; exit -1; fi

while read session;
do

    sessionId=$(echo $session | cut -d" " -f1)
    tumSample=$(echo $session | cut -d" " -f2)
    norSample=$(echo $session | cut -d" " -f3)
    projectName=$(echo $session | cut -d" " -f4)

    echo "downloading files for $sessionId"

    # check app has completed
    bs list appsessions --config "pmg-euc1" --filter-field Id --filter-term Â$sessionId

    # create directory for downloads
    if [ ! -e $projectName ]; then mkdir $projectName; fi

    # get dataset id from basespace using cli
    datasetId=$(~/bs get properties appsession --terse --config pmg-euc1 --id $sessionId --property-name Output.Datasets)

    # download results
    ~/bs download dataset --config pmg-euc1 --id $datasetId --output "$tumSample"

    # move downloaded tar to project directory
    if [ ! -e ./$projectName/$tumSample ]; then mkdir ./$projectName/$tumSample; fi
    mv ./"$tumSample".tar.gz ./$projectName/$tumSample/
    tar -xvzf ./$projectName/$tumSample/$tumSample.tar.gz -C ./$projectName/$tumSample/
    
done < ./appsessions.txt

# clean data
rm $projectName*.fastq

